PRAGMA foreign_keys=OFF;
ALTER TABLE tbl_users RENAME TO tbl_pos_users;
ALTER TABLE tbl_password_reset_tokens RENAME TO tbl_pos_password_reset_tokens;
ALTER TABLE tbl_cache RENAME TO tbl_pos_cache;
ALTER TABLE tbl_cache_locks RENAME TO tbl_pos_cache_locks;
ALTER TABLE tbl_jobs RENAME TO tbl_pos_jobs;
ALTER TABLE tbl_job_batches RENAME TO tbl_pos_job_batches;
ALTER TABLE tbl_failed_jobs RENAME TO tbl_pos_failed_jobs;
ALTER TABLE tbl_stores RENAME TO tbl_pos_stores;
ALTER TABLE tbl_categories RENAME TO tbl_pos_categories;
ALTER TABLE tbl_food_items RENAME TO tbl_pos_food_items;
ALTER TABLE tbl_orders RENAME TO tbl_pos_orders;
ALTER TABLE tbl_order_items RENAME TO tbl_pos_order_items;
ALTER TABLE tbl_store_devices RENAME TO tbl_pos_store_devices;
ALTER TABLE tbl_payments RENAME TO tbl_pos_payments;
ALTER TABLE tbl_sync_queue RENAME TO tbl_pos_sync_queue;
ALTER TABLE tbl_audit_logs RENAME TO tbl_pos_audit_logs;
ALTER TABLE tbl_personal_access_tokens RENAME TO tbl_pos_personal_access_tokens;
PRAGMA foreign_keys=ON;
